version: '3'

services:
  apigateway:
    container_name: apigateway
    build:
      context: apigateway
      dockerfile: Dockerfile
    environment:
      CLIENT: "https://client:7002"
      HEALTH_SERVICE: "http://healthservice:7003"
      MEALPLAN_SERVICE: "http://mealplanservice:7004"
      RECIPE_SERVICE: "http://recipeservice:7005"
      USER_SERVICE: "http://userservice:7006"
      FOOD_SERVICE: "http://foodservice:7007"
      INVENTORY_SERVICE: "http://inventoryservice:7008"
    depends_on:
      - healthservice
      #- foodservice
      #- inventoryservice
      #- mealplanservice
      - recipeservice
      - userservice
      - database
    deploy:
      replicas: 1

  healthservice:
    container_name: healthservice
    build:
      context: services/health-service
      dockerfile: Dockerfile
    environment:
      DB_CONN: "mysql+mysqlconnector://root:pass123@database:3306/health"
    depends_on:
      - database
  #foodservice:
  #  container_name: foodservice
  #  build:
  #    context: services/food-service/
  #    dockerfile: FoodService/Dockerfile
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://+:7007
  #    - DB_CONN="server=database;port=3306;database=inventory;user=root;password=pass123;"
  #    #- GATEWAY_URL=localhost:4000/foodservice/
  #  depends_on:
  #   - database
  #inventoryservice:
  #  container_name: inventoryservice
  #  build:
  #    context: services/inventory-service
  #    dockerfile: InventoryService/Dockerfile
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://+:7008
  #    - DB_CONN="server=database;port=3306;database=food;user=root;password=pass123;"
  #    #- GATEWAY_URL=localhost:4000/inventoryservice/
  #  depends_on:
  #    - database
  #mealplanservice:
  #  container_name: mealplanservice
  #  build:
  #    context: services/mealplan-service
  #    dockerfile: Dockerfile
  #  environment:
  #    HOST: database
  #    USER: root
  #    PASSWORD: pass123
  #    DATABASE: mealplan
  #  depends_on:
  #    - database
  recipeservice:
    container_name: recipeservice
    build:
      context: services/recipe-service
      dockerfile: Dockerfile
    environment:
      DB_CONN: "mysql+mysqlconnector://root:pass123@database:3306/recipes"
    depends_on:
      - database
  userservice:
    container_name: userservice
    build:
      context: services/user-service
      dockerfile: Dockerfile
    environment:
      DB_CONN: "mysql+mysqlconnector://root:pass123@database:3306/users"
    depends_on:
      - database

  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    #environment:
    depends_on:
      - apigateway


  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: pass123
    ports:
      - 3306:3306
    volumes:
      - "./database/init.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database/data.sql:/docker-entrypoint-initdb.d/2.sql"

  proxy:
    image: nginx:latest
    depends_on:
      - client
      - apigateway
    ports:
      - 443:443
    volumes:
    #  - ./cert:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf